include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-xwrt-doom
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

PKG_MAINTAINER:=Beaverfffan <1056715226@qq.com>
PKG_LICENSE:=MIT

LUCI_TITLE:=LuCI app for xwrt-doom (touchscreen Doom on the body panel)
LUCI_DEPENDS:=+xwrt-doom
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
